### ISSUE TITLE
Add getBalance RPC call

### ISSUE THREAD

**Issue by jarcodallo** [blockcoders/near-rpc-providers#5]
## Summary 

Get the most recent account's balance. RPC https://docs.near.org/docs/api/rpc/contracts#view-account

Example of request:
```json
{
  "jsonrpc": "2.0",
  "id": "dontcare",
  "method": "query",
  "params": {
    "request_type": "view_account",
    "finality": "final",
    "account_id": "blockcoders.testnet"
  }
}
```

## Expected behavior

When you call the function `getBalance()` should be return a `BigNumber` with the balance amount, Base provider [call](https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/base-provider.ts#L1209-L1225) . Add the corresponding unit/integration test

## How to do it?
You can get an example from [EtherscanProvider](https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/etherscan-provider.ts#L269-L275), Add a new case in [perform](https://github.com/blockcoders/near-rpc-providers/blob/main/src/near-rpc-provider.ts#L153) to send the request to the Near RPC.

**Comment by bzuker** [comment]
#6
